services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-umysql", "-pmysql" ]
      interval: 2s
      timeout: 5s
      retries: 10

  mysql9:
    image: mysql:9
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-umysql", "-pmysql" ]
      interval: 2s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  tapd-postgres:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5433:5433"
      - "9091:9091"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db?sslmode=disable
    command:
      - --driver=postgres
      - --listen=:5433
      - --upstream=postgres:5432
      - --grpc=:9091
    depends_on:
      postgres:
        condition: service_healthy

  tapd-mysql:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3307:3307"
      - "9092:9092"
    environment:
      DATABASE_URL: "mysql:mysql@tcp(mysql:3306)/db"
    command:
      - --driver=mysql
      - --listen=:3307
      - --upstream=mysql:3306
      - --grpc=:9092
    depends_on:
      mysql:
        condition: service_healthy

  tapd-mysql9:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3309:3309"
      - "9093:9093"
    environment:
      DATABASE_URL: "mysql:mysql@tcp(mysql9:3306)/db"
    command:
      - --driver=mysql
      - --listen=:3309
      - --upstream=mysql9:3306
      - --grpc=:9093
    depends_on:
      mysql9:
        condition: service_healthy
